[package]
name = "monies-macros"
version = "0.1.0"
authors = ["Denis Tsai <dt665m@gmail.com>"]
edition = "2018"

[dependencies]
rust_decimal = "1.7.0"
rust_decimal_macros = "1.7.0"

[dev-dependencies]
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
